DROP TABLE STUDENTS;
DROP TABLE BUILDINGS;
DROP TABLE TRAMSTOPS;

delete from USER_SDO_GEOM_METADATA where Table_Name='STUDENTS';
delete from USER_SDO_GEOM_METADATA where Table_Name='TRAMSTOPS';
delete from USER_SDO_GEOM_METADATA where Table_Name='BUILDINGS';